name: ci

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      release:
        description: Whether this is running as part of a release workflow.
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

env:
  GOVERSION: "1.26"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            goos: windows
            lint: true
          - os: ubuntu-latest
            goos: linux
            lint: true
          - os: macos-latest
            goos: darwin
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set up Go ${{ env.GOVERSION }}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ env.GOVERSION }}
          cache: false
      - name: Test
        run: GOOS=${{ matrix.goos }} go test ./... -cover -v
      - name: Smoke test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: ./tests/test.sh
  check:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    needs:
      - test
    steps:
      - name: Check
        run: |
          if [[ "${{ needs.test.result }}" == "success" ]]; then
            echo -e "\e[32mSuccess\e[0m"
          else
            echo -e "\e[31mFailed\e[0m"
            exit 1
          fi
